/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_example_filemanager_FileActivity */

#ifndef _Included_com_example_filemanager_FileActivity
#define _Included_com_example_filemanager_FileActivity
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_example_filemanager_FileActivity
 * Method:    readFile
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_example_filemanager_FileActivity_readFile
  (JNIEnv *, jobject, jstring);

/*
 * Class:     com_example_filemanager_FileActivity
 * Method:    editFile
 * Signature: (Ljava/lang/String;Ljava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_com_example_filemanager_FileActivity_editFile
  (JNIEnv *, jobject, jstring, jstring);

#ifdef __cplusplus
}
#endif
#endif
