/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_example_filemanager_PasswordService */

#ifndef _Included_com_example_filemanager_PasswordService
#define _Included_com_example_filemanager_PasswordService
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_example_filemanager_PasswordService
 * Method:    enterAndGetPassword
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_example_filemanager_PasswordService_enterAndGetPassword
  (JNIEnv *, jobject);

/*
 * Class:     com_example_filemanager_PasswordService
 * Method:    savePassword
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_com_example_filemanager_PasswordService_savePassword
  (JNIEnv *, jobject);

/*
 * Class:     com_example_filemanager_PasswordService
 * Method:    comparePassword
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_com_example_filemanager_PasswordService_comparePassword
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
