/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_example_filemanager_PasswordService_PasswordServiceBinder */

#ifndef _Included_com_example_filemanager_PasswordService_PasswordServiceBinder
#define _Included_com_example_filemanager_PasswordService_PasswordServiceBinder
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
