/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_example_filemanager_MainActivity */

#ifndef _Included_com_example_filemanager_MainActivity
#define _Included_com_example_filemanager_MainActivity
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_example_filemanager_MainActivity
 * Method:    passwordExists
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_com_example_filemanager_MainActivity_passwordExists
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
