/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_example_filemanager_FileListActivity */

#ifndef _Included_com_example_filemanager_FileListActivity
#define _Included_com_example_filemanager_FileListActivity
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_example_filemanager_FileListActivity
 * Method:    fetchFiles
 * Signature: (Ljava/lang/String;)Ljava/util/ArrayList;
 */
JNIEXPORT jobject JNICALL Java_com_example_filemanager_FileListActivity_fetchFiles
  (JNIEnv *, jobject, jstring);

/*
 * Class:     com_example_filemanager_FileListActivity
 * Method:    canOpenDir
 * Signature: (Ljava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_com_example_filemanager_FileListActivity_canOpenDir
  (JNIEnv *, jobject, jstring);

/*
 * Class:     com_example_filemanager_FileListActivity
 * Method:    deleteFile
 * Signature: (Ljava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_com_example_filemanager_FileListActivity_deleteFile
  (JNIEnv *, jobject, jstring);

/*
 * Class:     com_example_filemanager_FileListActivity
 * Method:    startSession
 * Signature: (I)Z
 */
JNIEXPORT jboolean JNICALL Java_com_example_filemanager_FileListActivity_startSession
  (JNIEnv *, jobject, jint);

#ifdef __cplusplus
}
#endif
#endif
